[package]
name = "steam_find"
version = "0.1.2"
authors = ["ManShanko <deathage@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ManShanko/steam_find"

[dependencies]
